import javafx.beans.property.IntegerProperty;

/**
 * This is a collection of items that can be found in a region marketplace.
 * The fields should be uniquely generated by the Marketplace when the marketplace
 * stock is created. buying and selling prices are unique to each marketplace
 */
public class StockEntry {
    private IntegerProperty quantity;
    private IntegerProperty buyingPrice;
    private IntegerProperty sellingPrice;
}
